---
title: Lucymethod.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Collin
description: Lucy Methopd Blog
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png
footer-links:
  dribbble: 
  email: 
  facebook: 
  flickr: 
  github: 
  instagram: 
  linkedin: 
  pinterest: 
  rss: 
  twitter: 
  stackoverflow: 
  youtube: 
  googleplus: 
disqus: 
google_analytics: 
url: http://lucymethod.github.io
baseurl: ''
permalink: "/:title"
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
gems:
- jekyll-sitemap
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
prose:
  ignore:
  - "/_layouts"
  - "/blog"
  - "/60"
  - "/index.html"
  - "contact"
  - "/about"
  - "/css"
  - "/images"
  - "/font"
  - "/.gitignore"
  - "/Q&A"
  siteurl: "http://lucymethod.github.io/blog"
  media: "http://lucymethod.github.io/postimgs"
  metadata:
    _posts:
    - name: layout
      field:
        element: hidden
        value: post
    - name: title
      field:
        element: text
        label: Title
    - name: author
      field:
        element: text
        label: Author
    - name: description
      field:
        element: text
        label: Description
    - name: image
      field:
        element: text
        label: Image Name
        value: test.jpg
